If:
  PathMatch: [.*\.c, .*\.h]

CompileFlags:
  Add: [-Wall, -Wextra]

---

If:
  PathMatch: [.*\.cpp, .*\.hpp]

CompileFlags:
  Add: [-Wall, -Wextra, -std=c++2b] # c++23

Index:
  StandardLibrary: Yes

---

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
